import {
  SiReact,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiCss,
  SiVite,
  SiDocker,
  SiPostgresql,
  SiNestjs,
  SiNodedotjs,
  SiPython,
  SiFastapi,
  SiPrisma,
  SiGithub,
  SiGit,
  SiVercel,
  SiMongodb,
  SiNextdotjs,
  SiKotlin,
  SiRedis,
  SiSocketdotio,
  SiStorybook,
  SiVitest,
  SiTailwindcss,
  SiGo,
  SiHaskell,
  SiMysql,
} from "react-icons/si";
import type { IconType } from "react-icons";

export const techIconMap: Record<string, IconType> = {
  React: SiReact,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  HTML5: SiHtml5,
  CSS: SiCss,
  "CSS3": SiCss,
  Vite: SiVite,
  Docker: SiDocker,
  "Docker Compose": SiDocker,
  PostgreSQL: SiPostgresql,
  NestJS: SiNestjs,
  "Node.js": SiNodedotjs,
  Python: SiPython,
  FastAPI: SiFastapi,
  "Prisma ORM": SiPrisma,
  Prisma: SiPrisma,
  GitHub: SiGithub,
  Git: SiGit,
  Vercel: SiVercel,
  MongoDB: SiMongodb,
  "Next.js": SiNextdotjs,
  Kotlin: SiKotlin,
  Redis: SiRedis,
  "Socket.io": SiSocketdotio,
  Storybook: SiStorybook,
  Vitest: SiVitest,
  "Tailwind CSS": SiTailwindcss,
  Go: SiGo,
  Haskell: SiHaskell,
  MySQL: SiMysql,
  MariaDB: SiMysql,
};
