import type { Technology, TechnologyGroup } from "@/modules/stack/domain/Technology";

export const technologies: Technology[] = [
  {
    id: "react",
    name: "React",
    level: "advanced",
    category: "frontend",
    description: "Librería principal para construir interfaces SPA con componentes reutilizables.",
    projectSlugs: ["retrosound-store", "tron-snake", "calculatron"],
    featured: true,
  },
  {
    id: "typescript",
    name: "TypeScript",
    level: "advanced",
    category: "language",
    description: "Tipado estático aplicado en frontend, modelos de dominio y componentes reutilizables.",
    projectSlugs: ["retrosound-store", "uvgenius", "calculatron"],
    featured: true,
  },
  {
    id: "javascript",
    name: "JavaScript",
    level: "advanced",
    category: "language",
    description: "Base del desarrollo web moderno y lógica de interacción en proyectos frontend.",
    projectSlugs: ["resident-evil-tracker", "tron-snake"],
    featured: true,
  },
  {
    id: "html5",
    name: "HTML5",
    level: "advanced",
    category: "frontend",
    description: "Estructura semántica para interfaces web accesibles y mantenibles.",
    projectSlugs: ["resident-evil-tracker", "tron-snake", "calculatron"],
  },
  {
    id: "css",
    name: "CSS",
    level: "advanced",
    category: "frontend",
    description: "Estilos responsivos, layout, animaciones y sistemas visuales personalizados.",
    projectSlugs: ["resident-evil-tracker", "tron-snake", "calculatron"],
    featured: true,
  },
  {
    id: "vite",
    name: "Vite",
    level: "advanced",
    category: "tool",
    description: "Bundler usado para crear SPAs rápidas con React y flujo de desarrollo moderno.",
    projectSlugs: ["retrosound-store", "tron-snake", "calculatron"],
    featured: true,
  },
  {
    id: "rest-apis",
    name: "REST APIs",
    level: "advanced",
    category: "api",
    description: "Diseño y consumo de endpoints para conectar frontend, backend y datos.",
    projectSlugs: ["retrosound-store", "uvgenius", "resident-evil-tracker", "tripwise-android"],
    featured: true,
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    level: "advanced",
    category: "database",
    description: "Base de datos relacional usada en proyectos full-stack con consultas y modelos reales.",
    projectSlugs: ["retrosound-store", "uvgenius", "resident-evil-tracker"],
    featured: true,
  },
  {
    id: "docker",
    name: "Docker",
    level: "advanced",
    category: "devops",
    description: "Contenedores para levantar servicios y entornos reproducibles de desarrollo.",
    projectSlugs: ["retrosound-store", "uvgenius", "resident-evil-tracker"],
    featured: true,
  },
  {
    id: "docker-compose",
    name: "Docker Compose",
    level: "advanced",
    category: "devops",
    description: "Orquestación local de servicios como backend, frontend, base de datos y herramientas.",
    projectSlugs: ["retrosound-store", "uvgenius"],
    featured: true,
  },
  {
    id: "git",
    name: "Git",
    level: "advanced",
    category: "tool",
    description: "Control de versiones con commits granulares, ramas y revisión de cambios.",
    projectSlugs: ["retrosound-store", "uvgenius", "tron-snake", "calculatron"],
    featured: true,
  },
  {
    id: "github",
    name: "GitHub",
    level: "advanced",
    category: "tool",
    description: "Gestión de repositorios, colaboración, historial técnico y publicación de código.",
    projectSlugs: ["uvgenius", "tron-snake", "calculatron"],
    featured: true,
  },
  {
    id: "nestjs",
    name: "NestJS",
    level: "advanced",
    category: "backend",
    description: "Framework backend modular usado para APIs estructuradas y mantenibles.",
    projectSlugs: ["retrosound-store", "uvgenius"],
    featured: true,
  },
  {
    id: "prisma-orm",
    name: "Prisma ORM",
    level: "advanced",
    category: "database",
    description: "ORM tipado para modelar entidades, consultas y operaciones CRUD.",
    projectSlugs: ["retrosound-store", "uvgenius"],
    featured: true,
  },
  {
    id: "tailwind-css",
    name: "Tailwind CSS",
    level: "advanced",
    category: "frontend",
    description: "Sistema utility-first usado para construir interfaces consistentes de forma rápida.",
    projectSlugs: ["retrosound-store"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    level: "intermediate",
    category: "frontend",
    description: "Framework React usado en aplicaciones con rutas, layouts y renderizado moderno.",
    projectSlugs: ["uvgenius"],
    featured: true,
  },
  {
    id: "react-router",
    name: "React Router",
    level: "intermediate",
    category: "frontend",
    description: "Enrutamiento client-side para SPAs con rutas dinámicas y navegación interna.",
    projectSlugs: ["tron-snake", "calculatron"],
  },
  {
    id: "tanstack-query",
    name: "TanStack Query",
    level: "intermediate",
    category: "frontend",
    description: "Manejo de server state, loading, error, cache y sincronización de datos.",
    projectSlugs: ["retrosound-store", "uvgenius"],
    featured: true,
  },
  {
    id: "radix-ui",
    name: "Radix UI",
    level: "intermediate",
    category: "frontend",
    description: "Primitivas accesibles para construir componentes de interfaz reutilizables.",
    projectSlugs: ["uvgenius"],
  },
  {
    id: "vitest",
    name: "Vitest",
    level: "intermediate",
    category: "testing",
    description: "Framework de pruebas para validar lógica y componentes en proyectos Vite.",
    projectSlugs: ["calculatron", "uvgenius"],
  },
  {
    id: "testing-library",
    name: "Testing Library",
    level: "intermediate",
    category: "testing",
    description: "Herramientas de testing orientadas al comportamiento visible para el usuario.",
    projectSlugs: ["calculatron"],
  },
  {
    id: "storybook",
    name: "Storybook",
    level: "intermediate",
    category: "tool",
    description: "Entorno para documentar y probar componentes visuales de forma aislada.",
    projectSlugs: ["calculatron"],
  },
  {
    id: "eslint",
    name: "ESLint",
    level: "intermediate",
    category: "tool",
    description: "Análisis estático para mantener consistencia y detectar errores en el código.",
    projectSlugs: ["retrosound-store", "uvgenius", "calculatron"],
  },
  {
    id: "jwt",
    name: "JWT",
    level: "intermediate",
    category: "backend",
    description: "Autenticación basada en tokens para proteger rutas y sesiones.",
    projectSlugs: ["retrosound-store", "uvgenius"],
  },
  {
    id: "cloudinary",
    name: "Cloudinary",
    level: "intermediate",
    category: "cloud",
    description: "Servicio para manejar imágenes y recursos multimedia en aplicaciones web o móviles.",
    projectSlugs: ["resident-evil-tracker", "tripwise-android"],
  },
  {
    id: "supabase",
    name: "Supabase",
    level: "intermediate",
    category: "database",
    description: "Plataforma backend-as-a-service usada para explorar bases de datos y autenticación.",
    projectSlugs: [],
  },
  {
    id: "vercel",
    name: "Vercel",
    level: "intermediate",
    category: "cloud",
    description: "Plataforma de deploy para frontend y APIs serverless.",
    projectSlugs: ["retrosound-store", "resident-evil-tracker", "tron-snake", "calculatron"],
    featured: true,
  },
  {
    id: "netlify",
    name: "Netlify",
    level: "intermediate",
    category: "cloud",
    description: "Plataforma de deploy frontend usada para publicar aplicaciones web estáticas.",
    projectSlugs: ["retrosound-store"],
  },
  {
    id: "python",
    name: "Python",
    level: "intermediate",
    category: "language",
    description: "Lenguaje usado para APIs, simulaciones y backend de servicios.",
    projectSlugs: ["resident-evil-tracker"],
  },
  {
    id: "fastapi",
    name: "FastAPI",
    level: "intermediate",
    category: "backend",
    description: "Framework Python para construir APIs rápidas y documentadas.",
    projectSlugs: ["resident-evil-tracker"],
    featured: true,
  },
  {
    id: "sqlmodel",
    name: "SQLModel",
    level: "intermediate",
    category: "database",
    description: "Capa de modelos SQL en Python combinando SQLAlchemy y Pydantic.",
    projectSlugs: ["resident-evil-tracker"],
  },
  {
    id: "pydantic",
    name: "Pydantic",
    level: "intermediate",
    category: "backend",
    description: "Validación de datos y modelos tipados para APIs en Python.",
    projectSlugs: ["resident-evil-tracker"],
  },
  {
    id: "kotlin",
    name: "Kotlin",
    level: "intermediate",
    category: "language",
    description: "Lenguaje usado para desarrollo Android moderno.",
    projectSlugs: ["tripwise-android"],
    featured: true,
  },
  {
    id: "jetpack-compose",
    name: "Jetpack Compose",
    level: "intermediate",
    category: "mobile",
    description: "Toolkit declarativo para construir interfaces Android modernas.",
    projectSlugs: ["tripwise-android"],
    featured: true,
  },
  {
    id: "retrofit",
    name: "Retrofit",
    level: "intermediate",
    category: "mobile",
    description: "Cliente HTTP para consumir APIs desde aplicaciones Android.",
    projectSlugs: ["tripwise-android"],
  },
  {
    id: "cpp",
    name: "C++",
    level: "intermediate",
    category: "language",
    description: "Lenguaje usado para programación de sistemas y proyectos con concurrencia.",
    projectSlugs: ["concurrent-tetris"],
    featured: true,
  },
  {
    id: "pthreads",
    name: "pthreads",
    level: "intermediate",
    category: "language",
    description: "API de hilos POSIX usada para manejar concurrencia en C/C++.",
    projectSlugs: ["concurrent-tetris"],
    featured: true,
  },
  {
    id: "ncurses",
    name: "ncurses",
    level: "intermediate",
    category: "tool",
    description: "Librería para interfaces de terminal y rendering en consola.",
    projectSlugs: ["concurrent-tetris"],
  },
  {
    id: "sdl2",
    name: "SDL2",
    level: "intermediate",
    category: "tool",
    description: "Librería multimedia usada para gráficos, ventanas y eventos.",
    projectSlugs: ["concurrent-tetris"],
  },
  {
    id: "redis",
    name: "Redis",
    level: "intermediate",
    category: "database",
    description: "Base en memoria usada para cache, sesiones o comunicación en tiempo real.",
    projectSlugs: ["uvgenius"],
  },
  {
    id: "socketio",
    name: "Socket.io",
    level: "intermediate",
    category: "backend",
    description: "Comunicación en tiempo real entre cliente y servidor.",
    projectSlugs: ["uvgenius"],
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    level: "intermediate",
    category: "devops",
    description: "Automatización de CI/CD y flujos de validación desde GitHub.",
    projectSlugs: ["uvgenius"],
  },
  {
    id: "framer-motion",
    name: "Framer Motion",
    level: "intermediate",
    category: "frontend",
    description: "Animaciones declarativas para interfaces React.",
    projectSlugs: [],
  },
  {
    id: "zod",
    name: "Zod",
    level: "intermediate",
    category: "tool",
    description: "Validación de esquemas y datos en TypeScript.",
    projectSlugs: ["uvgenius"],
  },
  {
    id: "postman",
    name: "Postman",
    level: "intermediate",
    category: "tool",
    description: "Pruebas manuales y documentación de APIs.",
    projectSlugs: ["retrosound-store", "resident-evil-tracker"],
  },
  {
    id: "metabase",
    name: "Metabase",
    level: "intermediate",
    category: "tool",
    description: "Herramienta de BI para dashboards, métricas y consultas SQL.",
    projectSlugs: ["retrosound-store"],
  },
  {
    id: "neo4j",
    name: "Neo4j",
    level: "intermediate",
    category: "database",
    description: "Base de datos de grafos usada para modelar relaciones y recomendaciones.",
    projectSlugs: [],
  },
  {
    id: "java",
    name: "Java",
    level: "intermediate",
    category: "language",
    description: "Lenguaje usado en proyectos académicos de estructuras de datos y backend básico.",
    projectSlugs: [],
  },
  {
    id: "react-native",
    name: "React Native",
    level: "basic",
    category: "mobile",
    description: "Framework para aplicaciones móviles multiplataforma con React.",
    projectSlugs: [],
  },
  {
    id: "laravel",
    name: "Laravel",
    level: "basic",
    category: "backend",
    description: "Framework PHP para desarrollo backend estructurado.",
    projectSlugs: [],
  },
  {
    id: "go",
    name: "Go",
    level: "basic",
    category: "language",
    description: "Lenguaje compilado para servicios concurrentes y backend.",
    projectSlugs: [],
  },
  {
    id: "haskell",
    name: "Haskell",
    level: "basic",
    category: "language",
    description: "Lenguaje funcional usado para aprender paradigmas declarativos.",
    projectSlugs: [],
  },
  {
    id: "mysql",
    name: "MySQL",
    level: "basic",
    category: "database",
    description: "Base de datos relacional ampliamente usada en aplicaciones web.",
    projectSlugs: [],
  },
  {
    id: "mariadb",
    name: "MariaDB",
    level: "basic",
    category: "database",
    description: "Sistema de base de datos relacional compatible con MySQL.",
    projectSlugs: [],
  },
  {
    id: "nodejs",
    name: "Node.js",
    level: "basic",
    category: "backend",
    description: "Runtime de JavaScript para ejecutar servicios backend.",
    projectSlugs: ["tripwise-android"],
  },
  {
    id: "express",
    name: "Express",
    level: "basic",
    category: "backend",
    description: "Framework minimalista para APIs HTTP en Node.js.",
    projectSlugs: ["tripwise-android"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    level: "basic",
    category: "database",
    description: "Base de datos NoSQL orientada a documentos.",
    projectSlugs: ["tripwise-android"],
  },
  {
    id: "mongoose",
    name: "Mongoose",
    level: "basic",
    category: "database",
    description: "ODM para modelar datos MongoDB desde Node.js.",
    projectSlugs: ["tripwise-android"],
  },
  {
    id: "openai-api",
    name: "OpenAI API",
    level: "basic",
    category: "api",
    description: "API para integrar modelos de IA en flujos de aplicación.",
    projectSlugs: ["tripwise-android"],
  },
  {
    id: "firebase",
    name: "Firebase",
    level: "basic",
    category: "cloud",
    description: "Plataforma backend-as-a-service para autenticación, base de datos y hosting.",
    projectSlugs: [],
  },
];

export const technologyGroups: TechnologyGroup[] = [
  {
    level: "advanced",
    title: "Avanzado",
    description:
      "Tecnologías que he usado directamente en proyectos principales, con decisiones técnicas defendibles y entregas completas.",
    technologies: technologies.filter((technology) => technology.level === "advanced"),
  },
  {
    level: "intermediate",
    title: "Medio",
    description:
      "Tecnologías que he aplicado en proyectos, integraciones o módulos específicos y que puedo explicar con contexto técnico.",
    technologies: technologies.filter((technology) => technology.level === "intermediate"),
  },
  {
    level: "basic",
    title: "Básico",
    description:
      "Tecnologías que conozco a nivel inicial, exploratorio o académico, útiles para seguir ampliando el stack.",
    technologies: technologies.filter((technology) => technology.level === "basic"),
  },
];
